repos:
  - repo: https://github.com/pycqa/pylint
    rev: v2.15.3
    hooks:
      - id: pylint
        additional_dependencies:
          - opencv-python
          - opencv-python-headless
          - tensorflow
          - imutils
          - numpy
          - Pillow
          - pytesseract
          - easyocr
        args: ["--rcfile=.pylintrc"]
  - repo: https://github.com/ambv/black
    rev: 22.8.0
    hooks:
      - id: black
        language_version: python3.10
